spring.datasource:
    hikari.maximum-pool-size: 4
    url: jdbc:postgresql://snsproject.cjtejhjcljia.ap-northeast-2.rds.amazonaws.com:5432/sns
    username: snsproject
    password:
    driver-class-name: org.postgresql.Driver

spring:
    jpa:
        show-sql: true
        database: postgresql
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQL10Dialect
        properties:
            hibernate:
                format_sql: true

    data:
        redis:
            url: redis://snsredis.0z1mzd.ng.0001.apn2.cache.amazonaws.com:6379

jwt:
    secret-key: sns_project.baekjihun_project.secret_key
    token.expired-time-ms: 2592000000
