spring.datasource:
    hikari.maximum-pool-size: 4
    url: jdbc:postgresql://snsproject.cjtejhjcljia.ap-northeast-2.rds.amazonaws.com:5432/sns
    username: snsproject
    password:
    driver-class-name: org.postgresql.Driver

spring:
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
        show-sql: true
