spring.datasource:
    hikari.maximum-pool-size: 4
    url: jdbc:postgresql://snsproject.cjtejhjcljia.ap-northeast-2.rds.amazonaws.com:5432/sns
    username: snsproject
    password: qorwlgns12
    driver-class-name: org.postgresql.Driver

spring:
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
        show-sql: true

jwt:
    secret-key: sns_project.baekjihun_project.secret_key
    token.expired-time-ms: 2592000000